//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.ClientCar = new HashSet<ClientCar>();
        }
    
        public int Id { get; set; }
        public string Mark { get; set; }
        public string Model { get; set; }
        public string CarKit { get; set; }
        public Nullable<double> EngineCapacity { get; set; }
        public string RegistrationNumber { get; set; }
        public string VIN_Code { get; set; }
        public int GraduationYear { get; set; }
        public string PlaceOfRegistration { get; set; }
        public Nullable<double> LoadCapacity { get; set; }
        public Nullable<int> NumberOfSeats { get; set; }
        public Nullable<bool> IsForTruck { get; set; }
        public Nullable<int> IdCarInsuranceType { get; set; }
    
        public virtual CarInsuranceType CarInsuranceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCar> ClientCar { get; set; }
    }
}
