//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarGlobalToInsuranceType
    {
        public int Id { get; set; }
        public int IdGlobalType { get; set; }
        public int IdInsuraceType { get; set; }
    
        public virtual CarGlobalType CarGlobalType { get; set; }
        public virtual CarInsuranceType CarInsuranceType { get; set; }
    }
}
