//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityOrCountryOfRegToZone
    {
        public int Id { get; set; }
        public bool IsUkraine { get; set; }
        public int IdCompany { get; set; }
        public Nullable<int> IdTSC { get; set; }
        public Nullable<int> IdInsuranceZoneOfReg { get; set; }
        public Nullable<int> IdCityOfRegistration { get; set; }
    
        public virtual CityOfRegistration CityOfRegistration { get; set; }
        public virtual Company Company { get; set; }
        public virtual InsuranceZoneOfRegistration InsuranceZoneOfRegistration { get; set; }
        public virtual TSC TSC { get; set; }
    }
}
