//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        public int Id { get; set; }
        public int IdCompany { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public int SummaryRait { get; set; }
        public int MTSBU_SummaryRait { get; set; }
        public int MTSBU_UregulationRait { get; set; }
        public int MTSBU_ComplaintLevel { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
