//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyIMG
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdImageType { get; set; }
        public string Path { get; set; }
        public int IdCompany { get; set; }
        public string ReferensToCompanyPage { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ImageType ImageType { get; set; }
    }
}
