//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public int IdDocumentType { get; set; }
        public int IdClient { get; set; }
        public string Series { get; set; }
        public string Number { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public string IssueBy { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual DocumentType DocumentType { get; set; }
    }
}
