//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceServiceBDEntities : DbContext
    {
        public InsuranceServiceBDEntities()
            : base("name=InsuranceServiceBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BonusMalus> BonusMalus { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<CarGlobalToInsuranceType> CarGlobalToInsuranceType { get; set; }
        public virtual DbSet<CarGlobalType> CarGlobalType { get; set; }
        public virtual DbSet<CarInsuranceType> CarInsuranceType { get; set; }
        public virtual DbSet<Chart> Chart { get; set; }
        public virtual DbSet<CityOfRegistration> CityOfRegistration { get; set; }
        public virtual DbSet<CityOrCountryOfRegToZone> CityOrCountryOfRegToZone { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientCar> ClientCar { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyContractTypes> CompanyContractTypes { get; set; }
        public virtual DbSet<CompanyDetail> CompanyDetail { get; set; }
        public virtual DbSet<CompanyFeature> CompanyFeature { get; set; }
        public virtual DbSet<CompanyFeatureToCompany> CompanyFeatureToCompany { get; set; }
        public virtual DbSet<CompanyIMG> CompanyIMG { get; set; }
        public virtual DbSet<CompanyMiddleman> CompanyMiddleman { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<ContractFranchise> ContractFranchise { get; set; }
        public virtual DbSet<ContractType> ContractType { get; set; }
        public virtual DbSet<CountryOfRegistration> CountryOfRegistration { get; set; }
        public virtual DbSet<DiscountByQuantity> DiscountByQuantity { get; set; }
        public virtual DbSet<DiscountForClientWithPrivilegies> DiscountForClientWithPrivilegies { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<Franchise> Franchise { get; set; }
        public virtual DbSet<ImageType> ImageType { get; set; }
        public virtual DbSet<InsuranceZoneOfRegistration> InsuranceZoneOfRegistration { get; set; }
        public virtual DbSet<K1> K1 { get; set; }
        public virtual DbSet<K2> K2 { get; set; }
        public virtual DbSet<K3> K3 { get; set; }
        public virtual DbSet<K4> K4 { get; set; }
        public virtual DbSet<K5> K5 { get; set; }
        public virtual DbSet<K6> K6 { get; set; }
        public virtual DbSet<K7> K7 { get; set; }
        public virtual DbSet<Middleman> Middleman { get; set; }
        public virtual DbSet<Privileges> Privileges { get; set; }
        public virtual DbSet<RegioneOfRegistration> RegioneOfRegistration { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TSC> TSC { get; set; }
    }
}
